services:
  lb:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_az_1
      - app_az_2

  app_az_1:
    build: .
    environment:
      - AZ_NAME=us-east-1a
      - INSTANCE_ID=instance-01

  app_az_2:
    build: .
    environment:
      - AZ_NAME=us-east-1b
      - INSTANCE_ID=instance-02
